name: Backend CI

on:
  push:
    branches: [ master ]
    paths:
      - 'shoes_houduan/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'shoes_houduan/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build (skip tests)
        working-directory: shoes_houduan
        run: mvn -B -DskipTests package
